config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(pages_params)

    if @page.save
      redirect_to pages_path
    else 
      render :new
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(pages_params)
      redirect_to pages_path
    else 
      render :edit
    end
  end

  def destroy
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

private

  def pages_params
    params.require(:page).permit(:title, :author, :description)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path, {class: "button"}%>
<%= link_to 'About', about_path, {class: "button"}%>
<%= link_to 'List', pages_path, {class: "button"}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :description %>
  <%= f.text_area :description %> 

  <%= f.submit class: "button" %>
<% end %> 

app/views/pages/index.html.erb
<h1 class="bottom"> To Do List </h1>
  <button class="waves-effect orange darken-4 btn-large"><%= link_to 'New Item', new_page_path %></button>
  <% @pages.each do |page| %>
  <h4><%= page.title %></h4>
  <p><%= page.description %><p>
  <%= link_to 'Show Page', page_path(page), {class: "button"} %>
  <%= link_to 'Edit Page', edit_page_path(page), {class: "button"} %>
  <%= link_to 'Destroy Page', page, {method: :delete, class: "button"} %>
<% end %>

app/views/pages/new.html.erb
<h1>New Page</h1>
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/pages/show.html.erb
<h1 class="bottom"><%= @page.title %></h1>
<h4><%= @page.author %></h4>
<p><%= @page.description %></p>
<%= link_to 'Back', pages_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
    <h1 class="bottom">Welcome!</h1>

<div class="wrapper">
  <h5>To do lists galore</h5>
  <p>Organize all your tasks with this modern application!</p>

  <h4>So many options on one application!</h4>
  <p>This plastic application is able to do all the tasks you have been looking for in a to do list manager. You can add items, edit them, and delete tasks completed!</p>
</div>

<button class="waves-effect orange darken-4 btn-large"><%= link_to 'Go to your list', pages_path %></button>